### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by adithyaov** [composewell/unicode-data#10]
# Core 

- [x] Fix the readme error `::`
- [x] Generate haddocks and check for any errors
- [x] Update stack resolver to 16.24
- [x] Add 8.8.4 and 8.10.2 to the CI 
- [x] Update tested-with accordingly
- [x] Improve haddocks
- [ ] Resolve all remaining issues
- [ ] Make a release tag 0.1.0
- [ ] Upload it to cabal
- [ ] Upload it to stack  

# Optional
  
- [x] Add a Github CI and Appyevor passing chip in the Readme
- [ ] Announce to haskell-cafe@haskell.org
